### ISSUE TITLE
Link to MLJ

### ISSUE THREAD

**Issue by KronosTheLate** [VaclavMacha/EvalMetrics.jl#8]
If I am not mistaken, the MLJ performance measures are more mature and/or feature-complete than this package:
https://alan-turing-institute.github.io/MLJ.jl/stable/performance_measures/

It does e.g. provide multiclass confusion matrices:
```
julia> using CategoricalArrays, MLJ

julia> yhat = rand(1:10, 100)|>CategoricalArray;

julia> y = rand(1:10, 100)|>CategoricalArray;

julia> ConfusionMatrix()(yhat, y)
┌ Warning: The classes are un-ordered,
│ using order: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
│ To suppress this warning, consider coercing to OrderedFactor.
└ @ MLJBase C:\Users\Dennis Bal\.julia\packages\MLJBase\rQDaq\src\measures\confusion_matrix.jl:122
10×10 Matrix{Int64}:
 3  0  1  1  0  1  3  2  2  2
 3  0  1  0  1  1  0  0  1  1
 0  0  1  0  1  1  0  1  0  2
 0  0  3  2  1  0  0  0  2  0
 1  2  0  0  4  0  2  0  1  2
 2  0  2  2  0  3  1  1  0  0
 3  2  2  1  1  0  0  0  0  2
 1  0  0  3  1  0  2  2  0  1
 2  1  2  2  2  1  1  2  1  0
 0  1  1  1  0  0  0  2  0  0
```

But this package is what comes first when googling confusion matrix julia.

I actually love the idea of a standalone EvalMetrics package. Or perhaps MLMetrics.
The best outcome as far as I can tell would be to have the functionality of MLJ put into a standalone package like this one, and then MLJ would simply add the package as a dependency.
Do you agree that something like this would be optimal?

Independent of any refactoring of MLJ, however, is the fact that a link to the page would be nice ^_^

**Comment by VaclavMacha** [comment]
That makes sense. Would you like to file a PR with the updated README?

**Comment by KronosTheLate** [comment]
Sorry, I did not get around to it. Thanks ^_^
