### ISSUE TITLE
DocStringExtensions version compat

### ISSUE THREAD

**Issue by frankier** [VaclavMacha/EvalMetrics.jl#9]
It looks like DocStringExtensions should have its compat updated to include 0.9. I think CompatHelper will make a PR when there is some activity in this repo. Does this issue count?

**Comment by frankier** [comment]
Hm. Looks like you might need to manually re-enable it https://github.com/VaclavMacha/EvalMetrics.jl/actions/workflows/CompatHelper.yml

@VaclavMacha Might it be possible for you to do this? I really like the simplicity of this package compared to the alternatives so would like to use it if I can use current DocStringExtensions

**Comment by VaclavMacha** [comment]
Can you @frankier  please check the following PR #15 ? The package should be more up-to-date now. Besides changing the compatibility constraints, I also removed some unnecessary dependencies.

**Comment by VaclavMacha** [comment]
Solved in #15

**Comment by frankier** [comment]
Thanks!
